### ISSUE TITLE
I am still not a collaborator

### ISSUE THREAD

**Issue by natis1** [BananaSky/VirusSimulator#1]
And therefore I still cannot push changes. Still. Seriously. Got the code at least. Visual Studio integration is pretty cool.

**Comment by BananaSky** [comment]
I tried taking you off the collaborator list and putting you on again, see if that works now
 


     On Saturday, October 3, 2015 6:25 PM, natis1 <notifications@github.com> wrote:
   

 And therefore I still cannot push changes. Still. Seriously. Got the code at least. Visual Studio integration is pretty cool.—

**Comment by natis1** [comment]
That's odd, it still doesn't show me on the list. Also whenever I try to push it gives me a 403 error. Did you add me to this project or the other one "Virus Sim" And why does "Virus Sim" still exist if we aren't even using it?

**Comment by BananaSky** [comment]
https://github.com/BananaSky/VirusSimulator/settings/collaborationYou should show up there (and you do, at least for me) You won't show up on the contributor list yet because you haven't pushed anythingThe 403 error is probably because of how you cloned the repository to your computerIf the "open in visual studio" button is what you're using, try doing the "clone to desktop" and then giving visual studio the location of the local repository you just cloned and see if that worksIf not, there's the link to the video in the other repository (which is why I kept it up), and that should help
 you:https://channel9.msdn.com/Series:ConnectOn-Demand/217Sent from Yahoo Mail for iPhoneOn Oct 4, 2015, 8:37:32 AM, natis1 wrote:That's odd, it still doesn't show me on the list. Also whenever I try to push it gives me a 403 error. Did you add me to this project or the other one "Virus Sim" And why does "Virus Sim" still exist if we aren't even using it?

**Comment by natis1** [comment]
There we go, got it working :).
